name: Run Luma-Magento Create an Account, Login, Choose Product, View and Update Shopping Cart, Proceed to Checkout every 00:00 Time
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/3-web-lamomagento/proceedToCheckoutMagento.cy.js

